name: app_version_cli
description: Get current app version from App Stores (Android and iOS) from within the command line interface
version: 0.1.0
homepage: https://github.com/emanuel-braz/app_version_cli
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.1.0
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  app_version: